package com.rv.entities;
// Generated 20 juil. 2019 10:43:59 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medecin generated by hbm2java
 */
@Entity
@Table(name = "medecin", catalog = "dbRdMedecins")
public class Medecin implements java.io.Serializable {

	private Integer codeMedecin;
	private String nom;
	private String tel;
	private Date dateEmbauche;
	private String specialite;

	public Medecin() {
	}

	public Medecin(String nom, String tel, Date dateEmbauche, String specialite) {
		this.nom = nom;
		this.tel = tel;
		this.dateEmbauche = dateEmbauche;
		this.specialite = specialite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codeMedecin", unique = true, nullable = false)
	public Integer getCodeMedecin() {
		return this.codeMedecin;
	}

	public void setCodeMedecin(Integer codeMedecin) {
		this.codeMedecin = codeMedecin;
	}

	@Column(name = "nom", length = 35)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "tel", length = 35)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEmbauche", length = 10)
	public Date getDateEmbauche() {
		return this.dateEmbauche;
	}

	public void setDateEmbauche(Date dateEmbauche) {
		this.dateEmbauche = dateEmbauche;
	}

	@Column(name = "specialite", length = 35)
	public String getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(String specialite) {
		this.specialite = specialite;
	}

}
