package com.rv.entities;
// Generated 20 juil. 2019 10:43:59 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "dbRdMedecins")
public class Patient implements java.io.Serializable {

	private Integer codePatient;
	private String nom;
	private String adresse;
	private Date dateNaissance;
	private String sexe;

	public Patient() {
	}

	public Patient(String nom, String adresse, Date dateNaissance, String sexe) {
		this.nom = nom;
		this.adresse = adresse;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codePatient", unique = true, nullable = false)
	public Integer getCodePatient() {
		return this.codePatient;
	}

	public void setCodePatient(Integer codePatient) {
		this.codePatient = codePatient;
	}

	@Column(name = "nom", length = 35)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse", length = 35)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissance", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "sexe", length = 35)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

}
